#!/usr/bin/env python3
"""Build a small, auditable MaleCNS circuit from the official v1.0 Feather files."""

from __future__ import annotations

import hashlib
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.feather as feather
import pyarrow.ipc as ipc


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = PROJECT_ROOT / "Data" / "raw"
GENERATED_DIR = PROJECT_ROOT / "Data" / "generated"
SWIFT_OUTPUT = (
    PROJECT_ROOT
    / "Sources"
    / "CyberFlySimulation"
    / "Generated"
    / "MaleCNSVisualCircuitData.swift"
)
JSON_OUTPUT = GENERATED_DIR / "male-cns-visual-steering-v1.json"

ANNOTATIONS = RAW_DIR / "body-annotations-male-cns-v1.0-minconf-0.5.feather"
NEUROTRANSMITTERS = RAW_DIR / "body-neurotransmitters-male-cns-v1.0.feather"
WEIGHTS = RAW_DIR / "connectome-weights-male-cns-v1.0-minconf-0.5.feather"

DATASET_ID = "male-cns:v1.0"
CIRCUIT_ID = "LoVP92→VES200m→DNg13"
TARGET_TYPES = ("LoVP92", "VES200m", "DNg13")
EXPECTED_COUNTS = {"LoVP92": 13, "VES200m": 12, "DNg13": 2}
SOURCE_URLS = {
    ANNOTATIONS.name: "https://storage.googleapis.com/flyem-male-cns/v1.0/connectome-data/flat-connectome/"
    + ANNOTATIONS.name,
    NEUROTRANSMITTERS.name: "https://storage.googleapis.com/flyem-male-cns/v1.0/connectome-data/flat-connectome/"
    + NEUROTRANSMITTERS.name,
    WEIGHTS.name: "https://storage.googleapis.com/flyem-male-cns/v1.0/connectome-data/flat-connectome/"
    + WEIGHTS.name,
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(8 * 1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def rows_for_types(path: Path, type_column: str) -> list[dict]:
    table = feather.read_table(path, memory_map=True)
    mask = pc.is_in(table[type_column], value_set=pa.array(TARGET_TYPES))
    return table.filter(mask).to_pylist()


def scan_selected_edges(path: Path, selected_ids: set[int]) -> list[dict]:
    selected = pa.array(sorted(selected_ids), type=pa.int64())
    edges: list[dict] = []
    with pa.memory_map(str(path), "r") as source:
        reader = ipc.open_file(source)
        for index in range(reader.num_record_batches):
            batch = reader.get_batch(index)
            mask = pc.and_(
                pc.is_in(batch.column("body_pre"), value_set=selected),
                pc.is_in(batch.column("body_post"), value_set=selected),
            )
            filtered = batch.filter(mask)
            for body_pre, body_post, weight in zip(
                filtered.column("body_pre").to_pylist(),
                filtered.column("body_post").to_pylist(),
                filtered.column("weight").to_pylist(),
                strict=True,
            ):
                edges.append(
                    {
                        "bodyPre": body_pre,
                        "bodyPost": body_post,
                        "weight": weight,
                        "provenance": "observed",
                    }
                )
    return sorted(edges, key=lambda edge: (edge["bodyPre"], edge["bodyPost"]))


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def build_swift(neurons: list[dict], edges: list[dict], source_hashes: dict[str, str]) -> str:
    lines = [
        "// Generated by Scripts/build_malecns_circuit.py. Do not hand-edit.",
        "import Foundation",
        "",
        "enum GeneratedMaleCNSVisualCircuitData {",
        f"    static let datasetID = {swift_string(DATASET_ID)}",
        f"    static let circuitID = {swift_string(CIRCUIT_ID)}",
        "    static let sourceSHA256: [String: String] = [",
    ]
    for name, digest in sorted(source_hashes.items()):
        lines.append(f"        {swift_string(name)}: {swift_string(digest)},")
    lines.extend(["    ]", "", "    static let neurons: [MaleCNSNeuronDefinition] = ["])
    for neuron in neurons:
        lines.append(
            "        .init("
            f"bodyID: {neuron['bodyId']}, "
            f"cellType: {swift_string(neuron['type'])}, "
            f"instance: {swift_string(neuron['instance'])}, "
            f"side: .{neuron['sideSwift']}, "
            f"neurotransmitter: .{neuron['neurotransmitterSwift']}, "
            f"neurotransmitterConfidence: {neuron['neurotransmitterConfidence']:.8f}),"
        )
    lines.extend(["    ]", "", "    static let edges: [MaleCNSSynapseDefinition] = ["])
    for edge in edges:
        lines.append(
            "        .init("
            f"bodyPre: {edge['bodyPre']}, bodyPost: {edge['bodyPost']}, weight: {edge['weight']}),"
        )
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> None:
    paths = (ANNOTATIONS, NEUROTRANSMITTERS, WEIGHTS)
    missing = [str(path) for path in paths if not path.is_file()]
    if missing:
        raise SystemExit("Missing official input files: " + ", ".join(missing))

    annotation_rows = rows_for_types(ANNOTATIONS, "type")
    nt_rows = rows_for_types(NEUROTRANSMITTERS, "cell_type")
    nt_by_body = {row["body"]: row for row in nt_rows}

    counts: dict[str, int] = defaultdict(int)
    neurons: list[dict] = []
    for row in annotation_rows:
        counts[row["type"]] += 1
        body_id = row["bodyId"]
        nt = nt_by_body.get(body_id)
        if nt is None:
            raise SystemExit(f"Missing neurotransmitter prediction for body {body_id}")
        transmitter = nt["consensus_nt"]
        transmitter_swift = {
            "acetylcholine": "acetylcholine",
            "glutamate": "glutamate",
            "gaba": "gaba",
            "dopamine": "dopamine",
            "serotonin": "serotonin",
            "octopamine": "octopamine",
        }.get(transmitter)
        if transmitter_swift is None:
            raise SystemExit(f"Unsupported transmitter {transmitter!r} for body {body_id}")
        neurons.append(
            {
                "bodyId": body_id,
                "type": row["type"],
                "instance": row["instance"],
                "side": row["somaSide"],
                "sideSwift": {"L": "left", "R": "right"}[row["somaSide"]],
                "status": row["status"],
                "neurotransmitter": transmitter,
                "neurotransmitterSwift": transmitter_swift,
                "neurotransmitterConfidence": nt["predicted_nt_confidence"],
                "identityProvenance": "observed",
                "neurotransmitterProvenance": "predicted",
            }
        )
    if dict(counts) != EXPECTED_COUNTS:
        raise SystemExit(f"Unexpected neuron counts: {dict(counts)} != {EXPECTED_COUNTS}")

    neurons.sort(key=lambda neuron: (neuron["type"], neuron["bodyId"]))
    selected_ids = {neuron["bodyId"] for neuron in neurons}
    edges = scan_selected_edges(WEIGHTS, selected_ids)
    type_by_body = {neuron["bodyId"]: neuron["type"] for neuron in neurons}

    aggregate: dict[tuple[str, str], dict[str, int]] = defaultdict(
        lambda: {"edgeCount": 0, "totalSynapses": 0}
    )
    for edge in edges:
        key = (type_by_body[edge["bodyPre"]], type_by_body[edge["bodyPost"]])
        aggregate[key]["edgeCount"] += 1
        aggregate[key]["totalSynapses"] += edge["weight"]
    for required in (("LoVP92", "VES200m"), ("VES200m", "DNg13")):
        if aggregate[required]["totalSynapses"] == 0:
            raise SystemExit(f"Required path is absent: {required[0]} -> {required[1]}")

    source_hashes = {path.name: sha256(path) for path in paths}
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    payload = {
        "schemaVersion": 1,
        "dataset": DATASET_ID,
        "circuit": CIRCUIT_ID,
        "generatedAt": generated_at,
        "sourceFiles": [
            {
                "name": path.name,
                "url": SOURCE_URLS[path.name],
                "bytes": path.stat().st_size,
                "sha256": source_hashes[path.name],
            }
            for path in paths
        ],
        "provenance": {
            "neuronIdentity": "observed",
            "synapseWeight": "observed",
            "neurotransmitter": "predicted",
            "dynamics": "literature-and-assumed",
        },
        "neuronCount": len(neurons),
        "edgeCount": len(edges),
        "aggregateEdges": [
            {
                "preType": pre_type,
                "postType": post_type,
                **values,
            }
            for (pre_type, post_type), values in sorted(aggregate.items())
        ],
        "neurons": [
            {
                key: value
                for key, value in neuron.items()
                if key not in {"sideSwift", "neurotransmitterSwift"}
            }
            for neuron in neurons
        ],
        "edges": edges,
    }

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    SWIFT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUTPUT.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    SWIFT_OUTPUT.write_text(
        build_swift(neurons, edges, source_hashes), encoding="utf-8"
    )

    print(
        json.dumps(
            {
                "dataset": DATASET_ID,
                "circuit": CIRCUIT_ID,
                "neurons": len(neurons),
                "edges": len(edges),
                "aggregateEdges": payload["aggregateEdges"],
                "json": str(JSON_OUTPUT.relative_to(PROJECT_ROOT)),
                "swift": str(SWIFT_OUTPUT.relative_to(PROJECT_ROOT)),
                "sourceSHA256": source_hashes,
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
